create table if not exists public.survey
(
    id   serial
        primary key,
    name varchar not null
);

alter table public.survey
    owner to postgres;

create table if not exists public.question
(
    id             serial
        constraint question_pk
            primary key,
    question_text  varchar           not null,
    answers_number integer default 1 not null
);

alter table public.question
    owner to postgres;

create table if not exists public.answer_text
(
    id          integer default nextval('answer_id_seq'::regclass) not null
        constraint text_of_the_answer_pk
            primary key,
    answer_text varchar                                            not null
);

alter table public.answer_text
    owner to postgres;

create table if not exists public.users
(
    id       integer default nextval('administrtor_administrtor_id_seq'::regclass) not null
        constraint users_pk
            primary key,
    name     varchar,
    login    varchar                                                               not null
        constraint login_unique
            unique,
    password varchar                                                               not null,
    role     varchar                                                               not null
);

alter table public.users
    owner to postgres;

create table if not exists public.answer
(
    survey_id      integer not null
        constraint answer_survey_id_fk
            references public.survey,
    question_id    integer not null
        constraint answer_question_id_fk
            references public.question,
    answer_text_id integer not null
        constraint answer_answer_text_id_fk
            references public.answer_text,
    user_id        integer not null
        constraint answer_users_id_fk
            references public.users,
    id             integer generated by default as identity
        constraint answer_pk
            primary key
);

alter table public.answer
    owner to postgres;

